site_name: polars-pairing
site_url: https://apcamargo.github.io/polars-pairing
repo_name: apcamargo/polars-pairing
repo_url: https://github.com/apcamargo/polars-pairing
nav:
  - Home: index.md
  - Reference: reference.md
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
extra_css:
  - stylesheets/extra.css
